/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedEntriesRouteImport } from './routes/_authed/entries'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsTokensRouteImport } from './routes/_authed/settings/tokens'
import { Route as AuthedSettingsTemplatesRouteImport } from './routes/_authed/settings/templates'
import { Route as AuthedSettingsProjectsRouteImport } from './routes/_authed/settings/projects'
import { Route as AuthedSettingsMembersRouteImport } from './routes/_authed/settings/members'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects.$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEntriesRoute = AuthedEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsTokensRoute = AuthedSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsTemplatesRoute = AuthedSettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsProjectsRoute = AuthedSettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsMembersRoute = AuthedSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/entries': typeof AuthedEntriesRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/templates': typeof AuthedTemplatesRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/projects': typeof AuthedSettingsProjectsRoute
  '/settings/templates': typeof AuthedSettingsTemplatesRoute
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/entries': typeof AuthedEntriesRoute
  '/reports': typeof AuthedReportsRoute
  '/templates': typeof AuthedTemplatesRoute
  '/': typeof AuthedIndexRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/members': typeof AuthedSettingsMembersRoute
  '/settings/projects': typeof AuthedSettingsProjectsRoute
  '/settings/templates': typeof AuthedSettingsTemplatesRoute
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/entries': typeof AuthedEntriesRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/templates': typeof AuthedTemplatesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/members': typeof AuthedSettingsMembersRoute
  '/_authed/settings/projects': typeof AuthedSettingsProjectsRoute
  '/_authed/settings/templates': typeof AuthedSettingsTemplatesRoute
  '/_authed/settings/tokens': typeof AuthedSettingsTokensRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/entries'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/projects/$projectId'
    | '/settings/general'
    | '/settings/members'
    | '/settings/projects'
    | '/settings/templates'
    | '/settings/tokens'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/entries'
    | '/reports'
    | '/templates'
    | '/'
    | '/projects/$projectId'
    | '/settings/general'
    | '/settings/members'
    | '/settings/projects'
    | '/settings/templates'
    | '/settings/tokens'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/account'
    | '/_authed/entries'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/_authed/templates'
    | '/_authed/'
    | '/_authed/projects/$projectId'
    | '/_authed/settings/general'
    | '/_authed/settings/members'
    | '/_authed/settings/projects'
    | '/_authed/settings/templates'
    | '/_authed/settings/tokens'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/entries': {
      id: '/_authed/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof AuthedEntriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/tokens': {
      id: '/_authed/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthedSettingsTokensRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/templates': {
      id: '/_authed/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthedSettingsTemplatesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/projects': {
      id: '/_authed/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthedSettingsProjectsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/members': {
      id: '/_authed/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthedSettingsMembersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsMembersRoute: typeof AuthedSettingsMembersRoute
  AuthedSettingsProjectsRoute: typeof AuthedSettingsProjectsRoute
  AuthedSettingsTemplatesRoute: typeof AuthedSettingsTemplatesRoute
  AuthedSettingsTokensRoute: typeof AuthedSettingsTokensRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsMembersRoute: AuthedSettingsMembersRoute,
  AuthedSettingsProjectsRoute: AuthedSettingsProjectsRoute,
  AuthedSettingsTemplatesRoute: AuthedSettingsTemplatesRoute,
  AuthedSettingsTokensRoute: AuthedSettingsTokensRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedEntriesRoute: typeof AuthedEntriesRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedTemplatesRoute: typeof AuthedTemplatesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedEntriesRoute: AuthedEntriesRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedTemplatesRoute: AuthedTemplatesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
